
[workspace]
resolver = "2"

members = [
	"dsl",
]

[workspace.package]
version = "0.1.0"    # the current version, obeying semver
authors = ["Alexander Seifarth, seifarth@titnc.de"]
license = "MPL-2"
